# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "comments", :force => true do |t|
    t.column "text", :string
    t.column "author", :string
    t.column "course_id", :integer
  end

  create_table "courses", :force => true do |t|
    t.column "name", :string
    t.column "distance", :float
    t.column "description", :string
  end

  create_table "geocodes", :force => true do |t|
    t.column "latitude", :float
    t.column "longitude", :float
    t.column "course_id", :integer
  end

end
